
          name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Continuous Integration (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar testes / Build
        run: |
          echo "Executando testes e validação do código..."
          # Adicione aqui os comandos de build/teste da sua aplicação (ex: npm test, python -m unittest, etc.)

  deploy:
    name: Continuous Delivery (CD)
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar Deploy
        run: |
          echo "Realizando o deploy da aplicação..."
          # Adicione aqui os comandos de deploy (ex: AWS, Vercel, Firebase, Docker, etc.)
          echo test, and deploy your project.
          
